name: Create a scratch org and run tests

on:
    push:
        branches:
            -   main

jobs:
    setup-scratch-org:
        name: Set up scratch org and run test classes
        runs-on: ubuntu-latest

        steps:
            # Checkout the repository
            -   name: Checkout repository
                uses: actions/checkout@v3
                
            # Install Salesforce CLI (SFDX)
            -   name: Install Salesforce CLI
                run: |
                    wget https://developer.salesforce.com/media/salesforce-cli/sf/channels/stable/sf-linux-x64.tar.xz
                    mkdir -p ~/cli/sf
                    tar xJf sf-linux-x64.tar.xz -C ~/cli/sf --strip-components 1
                    echo "$HOME/cli/sf/bin" >> $GITHUB_PATH

            # Verify Salesforce CLI Installation
            -   name: Verify Salesforce CLI Installation
                run: sf --version

            # Authenticate Dev hub
            -   name: Authenticate Dev Hub
                env:
                    SFDX_AUTH_URL: ${{ secrets.SFDX_AUTH_URL }}
                run: |
                    echo "$SFDX_AUTH_URL" > sf-auth-url.txt
                    sf org login sfdx-url --sfdx-url-file sf-auth-url.txt --alias DevHub

            # Create a scratch org
            -   name: Create scratch org
                run: |
                    sf org create scratch --definition-file config/project-scratch-def.json --duration-days 1 --alias MyScratchOrg --target-dev-hub DevHub
                    sf org display --alias MyScratchOrg
            
            # Deploy source to scratch org
            -   name: Deploy source
                run: |
                    sf project deploy start --target-org MyScratchOrg

            # Run all apex tests
            -   name: Run apex tests
                run: |
                    sf apex run test --target-org MyScratchOrg --wait 30 --output-dir test-results --result-format junit

            # Upload test results
            -   name: Upload test results
                uses: actions/upload-artifact@v3
                with:
                    name: apex-test-results
                    path: test-results/

            # Output access URL of scratch org
            -   name: Display scratch org login url
                run: |
                    echo "To access the scratch org, run the following command:"
                    echo "sf org open --alias MyScratchOrg"

